using poyosu.Configuration;
using SixLabors.ImageSharp.PixelFormats;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace poyosu.Builders
{
    public class SkinIniBuilder : Builder
    {
        public override string Folder => "ini";
        public override string Name => "skin.ini";

        public override async Task Generate(string path, Parameters parameters)
        {
            var builder = new StringBuilder();

            builder.AppendLine($"[General]");
            builder.AppendLine($"Name: poyosu! 2.0.0 dev build");
            builder.AppendLine($"Author: Poyo_SSB");
            builder.AppendLine($"Website: https://github.com/Poyo-SSB/poyosu");
            builder.AppendLine($"Version: 2.5");
            builder.AppendLine($"AnimationFramerate: {parameters.AnimationFramerate}");
            builder.AppendLine($"CursorExpand: 0");
            builder.AppendLine($"CursorRotate: 0");
            builder.AppendLine($"CursorTrailRotate: 0");
            builder.AppendLine($"AllowSliderBallTint: 0");
            builder.AppendLine();
            builder.AppendLine($"[Colours]");

            for (int i = 1; i < parameters.ComboColors.Length; i++)
            {
                Rgba32 color = parameters.ComboColors[i];
                builder.AppendLine($"Combo{i}: {color.R},{color.G},{color.B}");
            }
            Rgba32 firstColor = parameters.ComboColors[0];
            builder.AppendLine($"Combo{parameters.ComboColors.Length}: {firstColor.R},{firstColor.G},{firstColor.B}");

            builder.AppendLine();
            builder.AppendLine($"InputOverlayText: 255,255,255");
            builder.AppendLine($"SliderTrackOverride: 0,0,0");
            builder.AppendLine();
            builder.AppendLine($"SongSelectActiveText: 255,255,255");
            builder.AppendLine($"SongSelectInactiveText: 128,128,128");
            builder.AppendLine();
            builder.AppendLine($"SpinnerBackground: 255,255,255");
            builder.AppendLine();
            builder.AppendLine($"[Fonts]");
            builder.AppendLine($"HitCircleOverlap: -4");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 1");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 412");
            builder.AppendLine($"ColumnWidth: 28");
            builder.AppendLine($"ColumnLineWidth: 0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 0,14,19,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 0,48,63");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-blue");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-blue");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-blue");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 2");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 398");
            builder.AppendLine($"ColumnWidth: 28,28");
            builder.AppendLine($"ColumnSpacing: 1");
            builder.AppendLine($"SplitStages: 0");
            builder.AppendLine($"ColumnLineWidth: 0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 3");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 383");
            builder.AppendLine($"ColumnWidth: 28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 0,14,19,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 0,48,63");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-blue");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-blue");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-blue");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 4");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 369");
            builder.AppendLine($"ColumnWidth: 28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1");
            builder.AppendLine($"SplitStages: 0");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 2,25,0,255");
            builder.AppendLine($"Colour4: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 6,84,0");
            builder.AppendLine($"ColourLight4: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-green");
            builder.AppendLine($"NoteImage3L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-green");
            builder.AppendLine($"KeyImage3: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-green");
            builder.AppendLine($"KeyImage3D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 5");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 355");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1");
            builder.AppendLine($"SplitStages: 0");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 0,14,19,255");
            builder.AppendLine($"Colour4: 2,25,0,255");
            builder.AppendLine($"Colour5: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 0,48,63");
            builder.AppendLine($"ColourLight4: 6,84,0");
            builder.AppendLine($"ColourLight5: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-blue");
            builder.AppendLine($"NoteImage3L: mania-noteL-green");
            builder.AppendLine($"NoteImage4L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-blue");
            builder.AppendLine($"KeyImage3: mania-key-green");
            builder.AppendLine($"KeyImage4: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-blue");
            builder.AppendLine($"KeyImage3D: mania-keyD-green");
            builder.AppendLine($"KeyImage4D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 6");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 340");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1");
            builder.AppendLine($"SplitStages: 0");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 28,0,17,255");
            builder.AppendLine($"Colour5: 2,25,0,255");
            builder.AppendLine($"Colour6: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 94,0,57");
            builder.AppendLine($"ColourLight5: 6,84,0");
            builder.AppendLine($"ColourLight6: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-red");
            builder.AppendLine($"NoteImage4L: mania-noteL-green");
            builder.AppendLine($"NoteImage5L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-red");
            builder.AppendLine($"KeyImage4: mania-key-green");
            builder.AppendLine($"KeyImage5: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-red");
            builder.AppendLine($"KeyImage4D: mania-keyD-green");
            builder.AppendLine($"KeyImage5D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 7");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 326");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 0");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 0,14,19,255");
            builder.AppendLine($"Colour5: 28,0,17,255");
            builder.AppendLine($"Colour6: 2,25,0,255");
            builder.AppendLine($"Colour7: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 0,48,63");
            builder.AppendLine($"ColourLight5: 94,0,57");
            builder.AppendLine($"ColourLight6: 6,84,0");
            builder.AppendLine($"ColourLight7: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-blue");
            builder.AppendLine($"NoteImage4L: mania-noteL-red");
            builder.AppendLine($"NoteImage5L: mania-noteL-green");
            builder.AppendLine($"NoteImage6L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-blue");
            builder.AppendLine($"KeyImage4: mania-key-red");
            builder.AppendLine($"KeyImage5: mania-key-green");
            builder.AppendLine($"KeyImage6: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-blue");
            builder.AppendLine($"KeyImage4D: mania-keyD-red");
            builder.AppendLine($"KeyImage5D: mania-keyD-green");
            builder.AppendLine($"KeyImage6D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 8");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 311");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 0");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 2,25,0,255");
            builder.AppendLine($"Colour5: 2,25,0,255");
            builder.AppendLine($"Colour6: 28,0,17,255");
            builder.AppendLine($"Colour7: 2,25,0,255");
            builder.AppendLine($"Colour8: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 6,84,0");
            builder.AppendLine($"ColourLight5: 6,84,0");
            builder.AppendLine($"ColourLight6: 94,0,57");
            builder.AppendLine($"ColourLight7: 6,84,0");
            builder.AppendLine($"ColourLight8: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine($"NoteImage7: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine($"NoteImage7H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine($"NoteImage7T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-green");
            builder.AppendLine($"NoteImage4L: mania-noteL-green");
            builder.AppendLine($"NoteImage5L: mania-noteL-red");
            builder.AppendLine($"NoteImage6L: mania-noteL-green");
            builder.AppendLine($"NoteImage7L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-green");
            builder.AppendLine($"KeyImage4: mania-key-green");
            builder.AppendLine($"KeyImage5: mania-key-red");
            builder.AppendLine($"KeyImage6: mania-key-green");
            builder.AppendLine($"KeyImage7: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-green");
            builder.AppendLine($"KeyImage4D: mania-keyD-green");
            builder.AppendLine($"KeyImage5D: mania-keyD-red");
            builder.AppendLine($"KeyImage6D: mania-keyD-green");
            builder.AppendLine($"KeyImage7D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 9");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 296");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 0");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 2,25,0,255");
            builder.AppendLine($"Colour5: 0,14,19,255");
            builder.AppendLine($"Colour6: 2,25,0,255");
            builder.AppendLine($"Colour7: 28,0,17,255");
            builder.AppendLine($"Colour8: 2,25,0,255");
            builder.AppendLine($"Colour9: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 6,84,0");
            builder.AppendLine($"ColourLight5: 0,48,63");
            builder.AppendLine($"ColourLight6: 6,84,0");
            builder.AppendLine($"ColourLight7: 94,0,57");
            builder.AppendLine($"ColourLight8: 6,84,0");
            builder.AppendLine($"ColourLight9: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine($"NoteImage7: mania-note");
            builder.AppendLine($"NoteImage8: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine($"NoteImage7H: mania-note");
            builder.AppendLine($"NoteImage8H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine($"NoteImage7T: mania-note");
            builder.AppendLine($"NoteImage8T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-green");
            builder.AppendLine($"NoteImage4L: mania-noteL-blue");
            builder.AppendLine($"NoteImage5L: mania-noteL-green");
            builder.AppendLine($"NoteImage6L: mania-noteL-red");
            builder.AppendLine($"NoteImage7L: mania-noteL-green");
            builder.AppendLine($"NoteImage8L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-green");
            builder.AppendLine($"KeyImage4: mania-key-blue");
            builder.AppendLine($"KeyImage5: mania-key-green");
            builder.AppendLine($"KeyImage6: mania-key-red");
            builder.AppendLine($"KeyImage7: mania-key-green");
            builder.AppendLine($"KeyImage8: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-green");
            builder.AppendLine($"KeyImage4D: mania-keyD-blue");
            builder.AppendLine($"KeyImage5D: mania-keyD-green");
            builder.AppendLine($"KeyImage6D: mania-keyD-red");
            builder.AppendLine($"KeyImage7D: mania-keyD-green");
            builder.AppendLine($"KeyImage8D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 10");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 266");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 1");
            builder.AppendLine($"StageSeparation: 32");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 0,14,19,255");
            builder.AppendLine($"Colour4: 2,25,0,255");
            builder.AppendLine($"Colour5: 28,0,17,255");
            builder.AppendLine($"Colour6: 28,0,17,255");
            builder.AppendLine($"Colour7: 2,25,0,255");
            builder.AppendLine($"Colour8: 0,14,19,255");
            builder.AppendLine($"Colour9: 2,25,0,255");
            builder.AppendLine($"Colour10: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 0,48,63");
            builder.AppendLine($"ColourLight4: 6,84,0");
            builder.AppendLine($"ColourLight5: 94,0,57");
            builder.AppendLine($"ColourLight6: 94,0,57");
            builder.AppendLine($"ColourLight7: 6,84,0");
            builder.AppendLine($"ColourLight8: 0,48,63");
            builder.AppendLine($"ColourLight9: 6,84,0");
            builder.AppendLine($"ColourLight10: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine($"NoteImage7: mania-note");
            builder.AppendLine($"NoteImage8: mania-note");
            builder.AppendLine($"NoteImage9: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine($"NoteImage7H: mania-note");
            builder.AppendLine($"NoteImage8H: mania-note");
            builder.AppendLine($"NoteImage9H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine($"NoteImage7T: mania-note");
            builder.AppendLine($"NoteImage8T: mania-note");
            builder.AppendLine($"NoteImage9T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-blue");
            builder.AppendLine($"NoteImage3L: mania-noteL-green");
            builder.AppendLine($"NoteImage4L: mania-noteL-red");
            builder.AppendLine($"NoteImage5L: mania-noteL-red");
            builder.AppendLine($"NoteImage6L: mania-noteL-green");
            builder.AppendLine($"NoteImage7L: mania-noteL-blue");
            builder.AppendLine($"NoteImage8L: mania-noteL-green");
            builder.AppendLine($"NoteImage9L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-blue");
            builder.AppendLine($"KeyImage3: mania-key-green");
            builder.AppendLine($"KeyImage4: mania-key-red");
            builder.AppendLine($"KeyImage5: mania-key-red");
            builder.AppendLine($"KeyImage6: mania-key-green");
            builder.AppendLine($"KeyImage7: mania-key-blue");
            builder.AppendLine($"KeyImage8: mania-key-green");
            builder.AppendLine($"KeyImage9: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-blue");
            builder.AppendLine($"KeyImage3D: mania-keyD-green");
            builder.AppendLine($"KeyImage4D: mania-keyD-red");
            builder.AppendLine($"KeyImage5D: mania-keyD-red");
            builder.AppendLine($"KeyImage6D: mania-keyD-green");
            builder.AppendLine($"KeyImage7D: mania-keyD-blue");
            builder.AppendLine($"KeyImage8D: mania-keyD-green");
            builder.AppendLine($"KeyImage9D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 12");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 237");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 1");
            builder.AppendLine($"StageSeparation: 32");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 28,0,17,255");
            builder.AppendLine($"Colour5: 2,25,0,255");
            builder.AppendLine($"Colour6: 28,0,17,255");
            builder.AppendLine($"Colour7: 28,0,17,255");
            builder.AppendLine($"Colour8: 2,25,0,255");
            builder.AppendLine($"Colour9: 28,0,17,255");
            builder.AppendLine($"Colour10: 28,0,17,255");
            builder.AppendLine($"Colour11: 2,25,0,255");
            builder.AppendLine($"Colour12: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 94,0,57");
            builder.AppendLine($"ColourLight5: 6,84,0");
            builder.AppendLine($"ColourLight6: 94,0,57");
            builder.AppendLine($"ColourLight7: 94,0,57");
            builder.AppendLine($"ColourLight8: 6,84,0");
            builder.AppendLine($"ColourLight9: 94,0,57");
            builder.AppendLine($"ColourLight10: 94,0,57");
            builder.AppendLine($"ColourLight11: 6,84,0");
            builder.AppendLine($"ColourLight12: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine($"NoteImage7: mania-note");
            builder.AppendLine($"NoteImage8: mania-note");
            builder.AppendLine($"NoteImage9: mania-note");
            builder.AppendLine($"NoteImage10: mania-note");
            builder.AppendLine($"NoteImage11: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine($"NoteImage7H: mania-note");
            builder.AppendLine($"NoteImage8H: mania-note");
            builder.AppendLine($"NoteImage9H: mania-note");
            builder.AppendLine($"NoteImage10H: mania-note");
            builder.AppendLine($"NoteImage11H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine($"NoteImage7T: mania-note");
            builder.AppendLine($"NoteImage8T: mania-note");
            builder.AppendLine($"NoteImage9T: mania-note");
            builder.AppendLine($"NoteImage10T: mania-note");
            builder.AppendLine($"NoteImage11T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-red");
            builder.AppendLine($"NoteImage4L: mania-noteL-green");
            builder.AppendLine($"NoteImage5L: mania-noteL-red");
            builder.AppendLine($"NoteImage6L: mania-noteL-red");
            builder.AppendLine($"NoteImage7L: mania-noteL-green");
            builder.AppendLine($"NoteImage8L: mania-noteL-red");
            builder.AppendLine($"NoteImage9L: mania-noteL-red");
            builder.AppendLine($"NoteImage10L: mania-noteL-green");
            builder.AppendLine($"NoteImage11L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-red");
            builder.AppendLine($"KeyImage4: mania-key-green");
            builder.AppendLine($"KeyImage5: mania-key-red");
            builder.AppendLine($"KeyImage6: mania-key-red");
            builder.AppendLine($"KeyImage7: mania-key-green");
            builder.AppendLine($"KeyImage8: mania-key-red");
            builder.AppendLine($"KeyImage9: mania-key-red");
            builder.AppendLine($"KeyImage10: mania-key-green");
            builder.AppendLine($"KeyImage11: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-red");
            builder.AppendLine($"KeyImage4D: mania-keyD-green");
            builder.AppendLine($"KeyImage5D: mania-keyD-red");
            builder.AppendLine($"KeyImage6D: mania-keyD-red");
            builder.AppendLine($"KeyImage7D: mania-keyD-green");
            builder.AppendLine($"KeyImage8D: mania-keyD-red");
            builder.AppendLine($"KeyImage9D: mania-keyD-red");
            builder.AppendLine($"KeyImage10D: mania-keyD-green");
            builder.AppendLine($"KeyImage11D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 14");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 208");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28,28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1,1,1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 1");
            builder.AppendLine($"StageSeparation: 32");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 0,14,19,255");
            builder.AppendLine($"Colour5: 28,0,17,255");
            builder.AppendLine($"Colour6: 2,25,0,255");
            builder.AppendLine($"Colour7: 28,0,17,255");
            builder.AppendLine($"Colour8: 28,0,17,255");
            builder.AppendLine($"Colour9: 2,25,0,255");
            builder.AppendLine($"Colour10: 28,0,17,255");
            builder.AppendLine($"Colour11: 0,14,19,255");
            builder.AppendLine($"Colour12: 28,0,17,255");
            builder.AppendLine($"Colour13: 2,25,0,255");
            builder.AppendLine($"Colour14: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 0,48,63");
            builder.AppendLine($"ColourLight5: 94,0,57");
            builder.AppendLine($"ColourLight6: 6,84,0");
            builder.AppendLine($"ColourLight7: 94,0,57");
            builder.AppendLine($"ColourLight8: 94,0,57");
            builder.AppendLine($"ColourLight9: 6,84,0");
            builder.AppendLine($"ColourLight10: 94,0,57");
            builder.AppendLine($"ColourLight11: 0,48,63");
            builder.AppendLine($"ColourLight12: 94,0,57");
            builder.AppendLine($"ColourLight13: 6,84,0");
            builder.AppendLine($"ColourLight14: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine($"NoteImage7: mania-note");
            builder.AppendLine($"NoteImage8: mania-note");
            builder.AppendLine($"NoteImage9: mania-note");
            builder.AppendLine($"NoteImage10: mania-note");
            builder.AppendLine($"NoteImage11: mania-note");
            builder.AppendLine($"NoteImage12: mania-note");
            builder.AppendLine($"NoteImage13: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine($"NoteImage7H: mania-note");
            builder.AppendLine($"NoteImage8H: mania-note");
            builder.AppendLine($"NoteImage9H: mania-note");
            builder.AppendLine($"NoteImage10H: mania-note");
            builder.AppendLine($"NoteImage11H: mania-note");
            builder.AppendLine($"NoteImage12H: mania-note");
            builder.AppendLine($"NoteImage13H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine($"NoteImage7T: mania-note");
            builder.AppendLine($"NoteImage8T: mania-note");
            builder.AppendLine($"NoteImage9T: mania-note");
            builder.AppendLine($"NoteImage10T: mania-note");
            builder.AppendLine($"NoteImage11T: mania-note");
            builder.AppendLine($"NoteImage12T: mania-note");
            builder.AppendLine($"NoteImage13T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-blue");
            builder.AppendLine($"NoteImage4L: mania-noteL-red");
            builder.AppendLine($"NoteImage5L: mania-noteL-green");
            builder.AppendLine($"NoteImage6L: mania-noteL-red");
            builder.AppendLine($"NoteImage7L: mania-noteL-red");
            builder.AppendLine($"NoteImage8L: mania-noteL-green");
            builder.AppendLine($"NoteImage9L: mania-noteL-red");
            builder.AppendLine($"NoteImage10L: mania-noteL-blue");
            builder.AppendLine($"NoteImage11L: mania-noteL-red");
            builder.AppendLine($"NoteImage12L: mania-noteL-green");
            builder.AppendLine($"NoteImage13L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-blue");
            builder.AppendLine($"KeyImage4: mania-key-red");
            builder.AppendLine($"KeyImage5: mania-key-green");
            builder.AppendLine($"KeyImage6: mania-key-red");
            builder.AppendLine($"KeyImage7: mania-key-red");
            builder.AppendLine($"KeyImage8: mania-key-green");
            builder.AppendLine($"KeyImage9: mania-key-red");
            builder.AppendLine($"KeyImage10: mania-key-blue");
            builder.AppendLine($"KeyImage11: mania-key-red");
            builder.AppendLine($"KeyImage12: mania-key-green");
            builder.AppendLine($"KeyImage13: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-blue");
            builder.AppendLine($"KeyImage4D: mania-keyD-red");
            builder.AppendLine($"KeyImage5D: mania-keyD-green");
            builder.AppendLine($"KeyImage6D: mania-keyD-red");
            builder.AppendLine($"KeyImage7D: mania-keyD-red");
            builder.AppendLine($"KeyImage8D: mania-keyD-green");
            builder.AppendLine($"KeyImage9D: mania-keyD-red");
            builder.AppendLine($"KeyImage10D: mania-keyD-blue");
            builder.AppendLine($"KeyImage11D: mania-keyD-red");
            builder.AppendLine($"KeyImage12D: mania-keyD-green");
            builder.AppendLine($"KeyImage13D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 16");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 179");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 1");
            builder.AppendLine($"StageSeparation: 32");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 2,25,0,255");
            builder.AppendLine($"Colour5: 2,25,0,255");
            builder.AppendLine($"Colour6: 28,0,17,255");
            builder.AppendLine($"Colour7: 2,25,0,255");
            builder.AppendLine($"Colour8: 28,0,17,255");
            builder.AppendLine($"Colour9: 28,0,17,255");
            builder.AppendLine($"Colour10: 2,25,0,255");
            builder.AppendLine($"Colour11: 28,0,17,255");
            builder.AppendLine($"Colour12: 2,25,0,255");
            builder.AppendLine($"Colour13: 2,25,0,255");
            builder.AppendLine($"Colour14: 28,0,17,255");
            builder.AppendLine($"Colour15: 2,25,0,255");
            builder.AppendLine($"Colour16: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 6,84,0");
            builder.AppendLine($"ColourLight5: 6,84,0");
            builder.AppendLine($"ColourLight6: 94,0,57");
            builder.AppendLine($"ColourLight7: 6,84,0");
            builder.AppendLine($"ColourLight8: 94,0,57");
            builder.AppendLine($"ColourLight9: 94,0,57");
            builder.AppendLine($"ColourLight10: 6,84,0");
            builder.AppendLine($"ColourLight11: 94,0,57");
            builder.AppendLine($"ColourLight12: 6,84,0");
            builder.AppendLine($"ColourLight13: 6,84,0");
            builder.AppendLine($"ColourLight14: 94,0,57");
            builder.AppendLine($"ColourLight15: 6,84,0");
            builder.AppendLine($"ColourLight16: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine($"NoteImage7: mania-note");
            builder.AppendLine($"NoteImage8: mania-note");
            builder.AppendLine($"NoteImage9: mania-note");
            builder.AppendLine($"NoteImage10: mania-note");
            builder.AppendLine($"NoteImage11: mania-note");
            builder.AppendLine($"NoteImage12: mania-note");
            builder.AppendLine($"NoteImage13: mania-note");
            builder.AppendLine($"NoteImage14: mania-note");
            builder.AppendLine($"NoteImage15: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine($"NoteImage7H: mania-note");
            builder.AppendLine($"NoteImage8H: mania-note");
            builder.AppendLine($"NoteImage9H: mania-note");
            builder.AppendLine($"NoteImage10H: mania-note");
            builder.AppendLine($"NoteImage11H: mania-note");
            builder.AppendLine($"NoteImage12H: mania-note");
            builder.AppendLine($"NoteImage13H: mania-note");
            builder.AppendLine($"NoteImage14H: mania-note");
            builder.AppendLine($"NoteImage15H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine($"NoteImage7T: mania-note");
            builder.AppendLine($"NoteImage8T: mania-note");
            builder.AppendLine($"NoteImage9T: mania-note");
            builder.AppendLine($"NoteImage10T: mania-note");
            builder.AppendLine($"NoteImage11T: mania-note");
            builder.AppendLine($"NoteImage12T: mania-note");
            builder.AppendLine($"NoteImage13T: mania-note");
            builder.AppendLine($"NoteImage14T: mania-note");
            builder.AppendLine($"NoteImage15T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-green");
            builder.AppendLine($"NoteImage4L: mania-noteL-green");
            builder.AppendLine($"NoteImage5L: mania-noteL-red");
            builder.AppendLine($"NoteImage6L: mania-noteL-green");
            builder.AppendLine($"NoteImage7L: mania-noteL-red");
            builder.AppendLine($"NoteImage8L: mania-noteL-red");
            builder.AppendLine($"NoteImage9L: mania-noteL-green");
            builder.AppendLine($"NoteImage10L: mania-noteL-red");
            builder.AppendLine($"NoteImage11L: mania-noteL-green");
            builder.AppendLine($"NoteImage12L: mania-noteL-green");
            builder.AppendLine($"NoteImage13L: mania-noteL-red");
            builder.AppendLine($"NoteImage14L: mania-noteL-green");
            builder.AppendLine($"NoteImage15L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-green");
            builder.AppendLine($"KeyImage4: mania-key-green");
            builder.AppendLine($"KeyImage5: mania-key-red");
            builder.AppendLine($"KeyImage6: mania-key-green");
            builder.AppendLine($"KeyImage7: mania-key-red");
            builder.AppendLine($"KeyImage8: mania-key-red");
            builder.AppendLine($"KeyImage9: mania-key-green");
            builder.AppendLine($"KeyImage10: mania-key-red");
            builder.AppendLine($"KeyImage11: mania-key-green");
            builder.AppendLine($"KeyImage12: mania-key-green");
            builder.AppendLine($"KeyImage13: mania-key-red");
            builder.AppendLine($"KeyImage14: mania-key-green");
            builder.AppendLine($"KeyImage15: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-green");
            builder.AppendLine($"KeyImage4D: mania-keyD-green");
            builder.AppendLine($"KeyImage5D: mania-keyD-red");
            builder.AppendLine($"KeyImage6D: mania-keyD-green");
            builder.AppendLine($"KeyImage7D: mania-keyD-red");
            builder.AppendLine($"KeyImage8D: mania-keyD-red");
            builder.AppendLine($"KeyImage9D: mania-keyD-green");
            builder.AppendLine($"KeyImage10D: mania-keyD-red");
            builder.AppendLine($"KeyImage11D: mania-keyD-green");
            builder.AppendLine($"KeyImage12D: mania-keyD-green");
            builder.AppendLine($"KeyImage13D: mania-keyD-red");
            builder.AppendLine($"KeyImage14D: mania-keyD-green");
            builder.AppendLine($"KeyImage15D: mania-keyD-red");
            builder.AppendLine();
            builder.AppendLine($"[Mania]");
            builder.AppendLine($"Keys: 18");
            builder.AppendLine($"JudgementLine: 0");
            builder.AppendLine();
            builder.AppendLine($"BarlineHeight: 2");
            builder.AppendLine();
            builder.AppendLine($"ColumnStart: 150");
            builder.AppendLine($"ColumnWidth: 28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28");
            builder.AppendLine($"ColumnSpacing: 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1");
            builder.AppendLine($"SplitStages: 1");
            builder.AppendLine($"StageSeparation: 32");
            builder.AppendLine($"ColumnLineWidth: 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0");
            builder.AppendLine();
            builder.AppendLine($"LightPosition: 396");
            builder.AppendLine();
            builder.AppendLine($"ColourBarline: 255,204,33,100");
            builder.AppendLine();
            builder.AppendLine($"Colour1: 28,0,17,255");
            builder.AppendLine($"Colour2: 2,25,0,255");
            builder.AppendLine($"Colour3: 28,0,17,255");
            builder.AppendLine($"Colour4: 2,25,0,255");
            builder.AppendLine($"Colour5: 0,14,19,255");
            builder.AppendLine($"Colour6: 2,25,0,255");
            builder.AppendLine($"Colour7: 28,0,17,255");
            builder.AppendLine($"Colour8: 2,25,0,255");
            builder.AppendLine($"Colour9: 28,0,17,255");
            builder.AppendLine($"Colour10: 28,0,17,255");
            builder.AppendLine($"Colour11: 2,25,0,255");
            builder.AppendLine($"Colour12: 28,0,17,255");
            builder.AppendLine($"Colour13: 2,25,0,255");
            builder.AppendLine($"Colour14: 0,14,19,255");
            builder.AppendLine($"Colour15: 2,25,0,255");
            builder.AppendLine($"Colour16: 28,0,17,255");
            builder.AppendLine($"Colour17: 2,25,0,255");
            builder.AppendLine($"Colour18: 28,0,17,255");
            builder.AppendLine();
            builder.AppendLine($"ColourLight1: 94,0,57");
            builder.AppendLine($"ColourLight2: 6,84,0");
            builder.AppendLine($"ColourLight3: 94,0,57");
            builder.AppendLine($"ColourLight4: 6,84,0");
            builder.AppendLine($"ColourLight5: 0,48,63");
            builder.AppendLine($"ColourLight6: 6,84,0");
            builder.AppendLine($"ColourLight7: 94,0,57");
            builder.AppendLine($"ColourLight8: 6,84,0");
            builder.AppendLine($"ColourLight9: 94,0,57");
            builder.AppendLine($"ColourLight10: 94,0,57");
            builder.AppendLine($"ColourLight11: 6,84,0");
            builder.AppendLine($"ColourLight12: 94,0,57");
            builder.AppendLine($"ColourLight13: 6,84,0");
            builder.AppendLine($"ColourLight14: 0,48,63");
            builder.AppendLine($"ColourLight15: 6,84,0");
            builder.AppendLine($"ColourLight16: 94,0,57");
            builder.AppendLine($"ColourLight17: 6,84,0");
            builder.AppendLine($"ColourLight18: 94,0,57");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0: mania-note");
            builder.AppendLine($"NoteImage1: mania-note");
            builder.AppendLine($"NoteImage2: mania-note");
            builder.AppendLine($"NoteImage3: mania-note");
            builder.AppendLine($"NoteImage4: mania-note");
            builder.AppendLine($"NoteImage5: mania-note");
            builder.AppendLine($"NoteImage6: mania-note");
            builder.AppendLine($"NoteImage7: mania-note");
            builder.AppendLine($"NoteImage8: mania-note");
            builder.AppendLine($"NoteImage9: mania-note");
            builder.AppendLine($"NoteImage10: mania-note");
            builder.AppendLine($"NoteImage11: mania-note");
            builder.AppendLine($"NoteImage12: mania-note");
            builder.AppendLine($"NoteImage13: mania-note");
            builder.AppendLine($"NoteImage14: mania-note");
            builder.AppendLine($"NoteImage15: mania-note");
            builder.AppendLine($"NoteImage16: mania-note");
            builder.AppendLine($"NoteImage17: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0H: mania-note");
            builder.AppendLine($"NoteImage1H: mania-note");
            builder.AppendLine($"NoteImage2H: mania-note");
            builder.AppendLine($"NoteImage3H: mania-note");
            builder.AppendLine($"NoteImage4H: mania-note");
            builder.AppendLine($"NoteImage5H: mania-note");
            builder.AppendLine($"NoteImage6H: mania-note");
            builder.AppendLine($"NoteImage7H: mania-note");
            builder.AppendLine($"NoteImage8H: mania-note");
            builder.AppendLine($"NoteImage9H: mania-note");
            builder.AppendLine($"NoteImage10H: mania-note");
            builder.AppendLine($"NoteImage11H: mania-note");
            builder.AppendLine($"NoteImage12H: mania-note");
            builder.AppendLine($"NoteImage13H: mania-note");
            builder.AppendLine($"NoteImage14H: mania-note");
            builder.AppendLine($"NoteImage15H: mania-note");
            builder.AppendLine($"NoteImage16H: mania-note");
            builder.AppendLine($"NoteImage17H: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0T: mania-note");
            builder.AppendLine($"NoteImage1T: mania-note");
            builder.AppendLine($"NoteImage2T: mania-note");
            builder.AppendLine($"NoteImage3T: mania-note");
            builder.AppendLine($"NoteImage4T: mania-note");
            builder.AppendLine($"NoteImage5T: mania-note");
            builder.AppendLine($"NoteImage6T: mania-note");
            builder.AppendLine($"NoteImage7T: mania-note");
            builder.AppendLine($"NoteImage8T: mania-note");
            builder.AppendLine($"NoteImage9T: mania-note");
            builder.AppendLine($"NoteImage10T: mania-note");
            builder.AppendLine($"NoteImage11T: mania-note");
            builder.AppendLine($"NoteImage12T: mania-note");
            builder.AppendLine($"NoteImage13T: mania-note");
            builder.AppendLine($"NoteImage14T: mania-note");
            builder.AppendLine($"NoteImage15T: mania-note");
            builder.AppendLine($"NoteImage16T: mania-note");
            builder.AppendLine($"NoteImage17T: mania-note");
            builder.AppendLine();
            builder.AppendLine($"NoteImage0L: mania-noteL-red");
            builder.AppendLine($"NoteImage1L: mania-noteL-green");
            builder.AppendLine($"NoteImage2L: mania-noteL-red");
            builder.AppendLine($"NoteImage3L: mania-noteL-green");
            builder.AppendLine($"NoteImage4L: mania-noteL-blue");
            builder.AppendLine($"NoteImage5L: mania-noteL-green");
            builder.AppendLine($"NoteImage6L: mania-noteL-red");
            builder.AppendLine($"NoteImage7L: mania-noteL-green");
            builder.AppendLine($"NoteImage8L: mania-noteL-red");
            builder.AppendLine($"NoteImage9L: mania-noteL-red");
            builder.AppendLine($"NoteImage10L: mania-noteL-green");
            builder.AppendLine($"NoteImage11L: mania-noteL-red");
            builder.AppendLine($"NoteImage12L: mania-noteL-green");
            builder.AppendLine($"NoteImage13L: mania-noteL-blue");
            builder.AppendLine($"NoteImage14L: mania-noteL-green");
            builder.AppendLine($"NoteImage15L: mania-noteL-red");
            builder.AppendLine($"NoteImage16L: mania-noteL-green");
            builder.AppendLine($"NoteImage17L: mania-noteL-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0: mania-key-red");
            builder.AppendLine($"KeyImage1: mania-key-green");
            builder.AppendLine($"KeyImage2: mania-key-red");
            builder.AppendLine($"KeyImage3: mania-key-green");
            builder.AppendLine($"KeyImage4: mania-key-blue");
            builder.AppendLine($"KeyImage5: mania-key-green");
            builder.AppendLine($"KeyImage6: mania-key-red");
            builder.AppendLine($"KeyImage7: mania-key-green");
            builder.AppendLine($"KeyImage8: mania-key-red");
            builder.AppendLine($"KeyImage9: mania-key-red");
            builder.AppendLine($"KeyImage10: mania-key-green");
            builder.AppendLine($"KeyImage11: mania-key-red");
            builder.AppendLine($"KeyImage12: mania-key-green");
            builder.AppendLine($"KeyImage13: mania-key-blue");
            builder.AppendLine($"KeyImage14: mania-key-green");
            builder.AppendLine($"KeyImage15: mania-key-red");
            builder.AppendLine($"KeyImage16: mania-key-green");
            builder.AppendLine($"KeyImage17: mania-key-red");
            builder.AppendLine();
            builder.AppendLine($"KeyImage0D: mania-keyD-red");
            builder.AppendLine($"KeyImage1D: mania-keyD-green");
            builder.AppendLine($"KeyImage2D: mania-keyD-red");
            builder.AppendLine($"KeyImage3D: mania-keyD-green");
            builder.AppendLine($"KeyImage4D: mania-keyD-blue");
            builder.AppendLine($"KeyImage5D: mania-keyD-green");
            builder.AppendLine($"KeyImage6D: mania-keyD-red");
            builder.AppendLine($"KeyImage7D: mania-keyD-green");
            builder.AppendLine($"KeyImage8D: mania-keyD-red");
            builder.AppendLine($"KeyImage9D: mania-keyD-red");
            builder.AppendLine($"KeyImage10D: mania-keyD-green");
            builder.AppendLine($"KeyImage11D: mania-keyD-red");
            builder.AppendLine($"KeyImage12D: mania-keyD-green");
            builder.AppendLine($"KeyImage13D: mania-keyD-blue");
            builder.AppendLine($"KeyImage14D: mania-keyD-green");
            builder.AppendLine($"KeyImage15D: mania-keyD-red");
            builder.AppendLine($"KeyImage16D: mania-keyD-green");
            builder.AppendLine($"KeyImage17D: mania-keyD-red");

            File.WriteAllText(Path.Combine(path, $"skin.ini"), builder.ToString());

            await Task.CompletedTask;
        }
    }
}
